spring:
  application:
    name: Hospital Management System
  datasource:
    url: jdbc:postgresql://localhost:5432/hms
    username: postgres
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:qazwsxedcrfvtgbyhnujmikolp1946273058}